// oxlint-disable max-lines @unocss-ignore
export const countryShortNames = [
  'af',
  'al',
  'dz',
  'ad',
  'ao',
  'ar',
  'am',
  'aw',
  'au',
  'at',
  'az',
  'bh',
  'bd',
  'by',
  'be',
  'bz',
  'bj',
  'bt',
  'bo',
  'ba',
  'bw',
  'br',
  'io',
  'bn',
  'bg',
  'bf',
  'bi',
  'kh',
  'cm',
  'cv',
  'cf',
  'td',
  'cl',
  'cn',
  'co',
  'km',
  'cg',
  'cd',
  'ck',
  'cr',
  'ci',
  'hr',
  'cu',
  'cw',
  'cy',
  'cz',
  'dk',
  'dj',
  'ec',
  'eg',
  'sv',
  'gq',
  'er',
  'ee',
  'sz',
  'et',
  'fk',
  'fo',
  'fj',
  'fi',
  'fr',
  'gf',
  'pf',
  'ga',
  'gm',
  'ge',
  'de',
  'gh',
  'gi',
  'gr',
  'gl',
  'gp',
  'gt',
  'gn',
  'gw',
  'gy',
  'ht',
  'hn',
  'hk',
  'hu',
  'is',
  'in',
  'id',
  'ir',
  'iq',
  'ie',
  'il',
  'it',
  'jp',
  'jo',
  'ke',
  'ki',
  'xk',
  'kw',
  'kg',
  'la',
  'lv',
  'lb',
  'ls',
  'lr',
  'ly',
  'li',
  'lt',
  'lu',
  'mo',
  'mg',
  'mw',
  'my',
  'mv',
  'ml',
  'mt',
  'mh',
  'mq',
  'mr',
  'mu',
  'yt',
  'mx',
  'fm',
  'md',
  'mc',
  'mn',
  'me',
  'ma',
  'mz',
  'mm',
  'na',
  'nr',
  'np',
  'nl',
  'nc',
  'nz',
  'ni',
  'ne',
  'ng',
  'nu',
  'nf',
  'kp',
  'mk',
  'no',
  'om',
  'pk',
  'pw',
  'ps',
  'pa',
  'pg',
  'py',
  'pe',
  'ph',
  'pl',
  'pt',
  'qa',
  'ro',
  'ru',
  'rw',
  'ws',
  'sm',
  'st',
  'sa',
  'sn',
  'rs',
  'sc',
  'sl',
  'sg',
  'sk',
  'si',
  'sb',
  'so',
  'za',
  'kr',
  'ss',
  'es',
  'lk',
  'sh',
  'pm',
  'sd',
  'sr',
  'se',
  'ch',
  'sy',
  'tw',
  'tj',
  'tz',
  'th',
  'tl',
  'tg',
  'tk',
  'to',
  'tn',
  'tr',
  'tm',
  'tv',
  'ug',
  'ua',
  'ae',
  'gb',
  'us',
  'uy',
  'uz',
  'vu',
  've',
  'vn',
  'wf',
  'ye',
  'zm',
  'zw',
] as const;

const flagUrl = 'https://cdn.jsdelivr.net/npm/flag-icons@7.5.0/flags/4x3';
const getFlagIcon = (name: string): string => `${flagUrl}/${name}.svg`;

export type Iso2 = (typeof countryShortNames)[number];

type CountryData = {
  name: string;
  code: number;
  flag: string;
};

export const countryTranslations: Record<Iso2, CountryData> = {
  af: {
    name: 'Afghanistan',
    code: 93,
    flag: getFlagIcon('af'),
  },
  al: {
    name: 'Albania',
    code: 355,
    flag: getFlagIcon('al'),
  },
  dz: {
    name: 'Algeria',
    code: 213,
    flag: getFlagIcon('dz'),
  },
  ad: {
    name: 'Andorra',
    code: 376,
    flag: getFlagIcon('ad'),
  },
  ao: {
    name: 'Angola',
    code: 244,
    flag: getFlagIcon('ao'),
  },
  ar: {
    name: 'Argentina',
    code: 54,
    flag: getFlagIcon('ar'),
  },
  am: {
    name: 'Armenia',
    code: 374,
    flag: getFlagIcon('am'),
  },
  aw: {
    name: 'Aruba',
    code: 297,
    flag: getFlagIcon('aw'),
  },
  au: {
    name: 'Australia',
    code: 61,
    flag: getFlagIcon('au'),
  },
  at: {
    name: 'Austria',
    code: 43,
    flag: getFlagIcon('at'),
  },
  az: {
    name: 'Azerbaijan',
    code: 994,
    flag: getFlagIcon('az'),
  },
  bh: {
    name: 'Bahrain',
    code: 973,
    flag: getFlagIcon('bh'),
  },
  bd: {
    name: 'Bangladesh',
    code: 880,
    flag: getFlagIcon('bd'),
  },
  by: {
    name: 'Belarus',
    code: 375,
    flag: getFlagIcon('by'),
  },
  be: {
    name: 'Belgium',
    code: 32,
    flag: getFlagIcon('be'),
  },
  bz: {
    name: 'Belize',
    code: 501,
    flag: getFlagIcon('bz'),
  },
  bj: {
    name: 'Benin',
    code: 229,
    flag: getFlagIcon('bj'),
  },
  bt: {
    name: 'Bhutan',
    code: 975,
    flag: getFlagIcon('bt'),
  },
  bo: {
    name: 'Bolivia',
    code: 591,
    flag: getFlagIcon('bo'),
  },
  ba: {
    name: 'Bosnia & Herzegovina',
    code: 387,
    flag: getFlagIcon('ba'),
  },
  bw: {
    name: 'Botswana',
    code: 267,
    flag: getFlagIcon('bw'),
  },
  br: {
    name: 'Brazil',
    code: 55,
    flag: getFlagIcon('br'),
  },
  io: {
    name: 'British Indian Ocean Territory',
    code: 246,
    flag: getFlagIcon('io'),
  },
  bn: {
    name: 'Brunei',
    code: 673,
    flag: getFlagIcon('bn'),
  },
  bg: {
    name: 'Bulgaria',
    code: 359,
    flag: getFlagIcon('bg'),
  },
  bf: {
    name: 'Burkina Faso',
    code: 226,
    flag: getFlagIcon('bf'),
  },
  bi: {
    name: 'Burundi',
    code: 257,
    flag: getFlagIcon('bi'),
  },
  kh: {
    name: 'Cambodia',
    code: 855,
    flag: getFlagIcon('kh'),
  },
  cm: {
    name: 'Cameroon',
    code: 237,
    flag: getFlagIcon('cm'),
  },
  cv: {
    name: 'Cape Verde',
    code: 238,
    flag: getFlagIcon('cv'),
  },
  cf: {
    name: 'Central African Republic',
    code: 236,
    flag: getFlagIcon('cf'),
  },
  td: {
    name: 'Chad',
    code: 235,
    flag: getFlagIcon('td'),
  },
  cl: {
    name: 'Chile',
    code: 56,
    flag: getFlagIcon('cl'),
  },
  cn: {
    name: 'China',
    code: 86,
    flag: getFlagIcon('cn'),
  },
  co: {
    name: 'Colombia',
    code: 57,
    flag: getFlagIcon('co'),
  },
  km: {
    name: 'Comoros',
    code: 269,
    flag: getFlagIcon('km'),
  },
  cg: {
    name: 'Congo - Brazzaville',
    code: 242,
    flag: getFlagIcon('cg'),
  },
  cd: {
    name: 'Congo - Kinshasa',
    code: 243,
    flag: getFlagIcon('cd'),
  },
  ck: {
    name: 'Cook Islands',
    code: 682,
    flag: getFlagIcon('ck'),
  },
  cr: {
    name: 'Costa Rica',
    code: 506,
    flag: getFlagIcon('cr'),
  },
  ci: {
    name: 'Côte d’Ivoire',
    code: 225,
    flag: getFlagIcon('ci'),
  },
  hr: {
    name: 'Croatia',
    code: 385,
    flag: getFlagIcon('hr'),
  },
  cu: {
    name: 'Cuba',
    code: 53,
    flag: getFlagIcon('cu'),
  },
  cw: {
    name: 'Curaçao',
    code: 599,
    flag: getFlagIcon('cw'),
  },
  cy: {
    name: 'Cyprus',
    code: 357,
    flag: getFlagIcon('cy'),
  },
  cz: {
    name: 'Czechia',
    code: 420,
    flag: getFlagIcon('cz'),
  },
  dk: {
    name: 'Denmark',
    code: 45,
    flag: getFlagIcon('dk'),
  },
  dj: {
    name: 'Djibouti',
    code: 253,
    flag: getFlagIcon('dj'),
  },
  ec: {
    name: 'Ecuador',
    code: 593,
    flag: getFlagIcon('ec'),
  },
  eg: {
    name: 'Egypt',
    code: 20,
    flag: getFlagIcon('eg'),
  },
  sv: {
    name: 'El Salvador',
    code: 503,
    flag: getFlagIcon('sv'),
  },
  gq: {
    name: 'Equatorial Guinea',
    code: 240,
    flag: getFlagIcon('gq'),
  },
  er: {
    name: 'Eritrea',
    code: 291,
    flag: getFlagIcon('er'),
  },
  ee: {
    name: 'Estonia',
    code: 372,
    flag: getFlagIcon('ee'),
  },
  sz: {
    name: 'Eswatini',
    code: 268,
    flag: getFlagIcon('sz'),
  },
  et: {
    name: 'Ethiopia',
    code: 251,
    flag: getFlagIcon('et'),
  },
  fk: {
    name: 'Falkland Islands',
    code: 500,
    flag: getFlagIcon('fk'),
  },
  fo: {
    name: 'Faroe Islands',
    code: 298,
    flag: getFlagIcon('fo'),
  },
  fj: {
    name: 'Fiji',
    code: 679,
    flag: getFlagIcon('fj'),
  },
  fi: {
    name: 'Finland',
    code: 358,
    flag: getFlagIcon('fi'),
  },
  fr: {
    name: 'France',
    code: 33,
    flag: getFlagIcon('fr'),
  },
  gf: {
    name: 'French Guiana',
    code: 594,
    flag: getFlagIcon('gf'),
  },
  pf: {
    name: 'French Polynesia',
    code: 689,
    flag: getFlagIcon('pf'),
  },
  ga: {
    name: 'Gabon',
    code: 241,
    flag: getFlagIcon('ga'),
  },
  gm: {
    name: 'Gambia',
    code: 220,
    flag: getFlagIcon('gm'),
  },
  ge: {
    name: 'Georgia',
    code: 995,
    flag: getFlagIcon('ge'),
  },
  de: {
    name: 'Germany',
    code: 49,
    flag: getFlagIcon('de'),
  },
  gh: {
    name: 'Ghana',
    code: 233,
    flag: getFlagIcon('gh'),
  },
  gi: {
    name: 'Gibraltar',
    code: 350,
    flag: getFlagIcon('gi'),
  },
  gr: {
    name: 'Greece',
    code: 30,
    flag: getFlagIcon('gr'),
  },
  gl: {
    name: 'Greenland',
    code: 299,
    flag: getFlagIcon('gl'),
  },
  gp: {
    name: 'Guadeloupe',
    code: 590,
    flag: getFlagIcon('gp'),
  },
  gt: {
    name: 'Guatemala',
    code: 502,
    flag: getFlagIcon('gt'),
  },
  gn: {
    name: 'Guinea',
    code: 224,
    flag: getFlagIcon('gn'),
  },
  gw: {
    name: 'Guinea-Bissau',
    code: 245,
    flag: getFlagIcon('gw'),
  },
  gy: {
    name: 'Guyana',
    code: 592,
    flag: getFlagIcon('gy'),
  },
  ht: {
    name: 'Haiti',
    code: 509,
    flag: getFlagIcon('ht'),
  },
  hn: {
    name: 'Honduras',
    code: 504,
    flag: getFlagIcon('hn'),
  },
  hk: {
    name: 'Hong Kong SAR China',
    code: 852,
    flag: getFlagIcon('hk'),
  },
  hu: {
    name: 'Hungary',
    code: 36,
    flag: getFlagIcon('hu'),
  },
  is: {
    name: 'Iceland',
    code: 354,
    flag: getFlagIcon('is'),
  },
  in: {
    name: 'India',
    code: 91,
    flag: getFlagIcon('in'),
  },
  id: {
    name: 'Indonesia',
    code: 62,
    flag: getFlagIcon('id'),
  },
  ir: {
    name: 'Iran',
    code: 98,
    flag: getFlagIcon('ir'),
  },
  iq: {
    name: 'Iraq',
    code: 964,
    flag: getFlagIcon('iq'),
  },
  ie: {
    name: 'Ireland',
    code: 353,
    flag: getFlagIcon('ie'),
  },
  il: {
    name: 'Israel',
    code: 972,
    flag: getFlagIcon('il'),
  },
  it: {
    name: 'Italy',
    code: 39,
    flag: getFlagIcon('it'),
  },
  jp: {
    name: 'Japan',
    code: 81,
    flag: getFlagIcon('jp'),
  },
  jo: {
    name: 'Jordan',
    code: 962,
    flag: getFlagIcon('jo'),
  },
  ke: {
    name: 'Kenya',
    code: 254,
    flag: getFlagIcon('ke'),
  },
  ki: {
    name: 'Kiribati',
    code: 686,
    flag: getFlagIcon('ki'),
  },
  xk: {
    name: 'Kosovo',
    code: 383,
    flag: getFlagIcon('xk'),
  },
  kw: {
    name: 'Kuwait',
    code: 965,
    flag: getFlagIcon('kw'),
  },
  kg: {
    name: 'Kyrgyzstan',
    code: 996,
    flag: getFlagIcon('kg'),
  },
  la: {
    name: 'Laos',
    code: 856,
    flag: getFlagIcon('la'),
  },
  lv: {
    name: 'Latvia',
    code: 371,
    flag: getFlagIcon('lv'),
  },
  lb: {
    name: 'Lebanon',
    code: 961,
    flag: getFlagIcon('lb'),
  },
  ls: {
    name: 'Lesotho',
    code: 266,
    flag: getFlagIcon('ls'),
  },
  lr: {
    name: 'Liberia',
    code: 231,
    flag: getFlagIcon('lr'),
  },
  ly: {
    name: 'Libya',
    code: 218,
    flag: getFlagIcon('ly'),
  },
  li: {
    name: 'Liechtenstein',
    code: 423,
    flag: getFlagIcon('li'),
  },
  lt: {
    name: 'Lithuania',
    code: 370,
    flag: getFlagIcon('lt'),
  },
  lu: {
    name: 'Luxembourg',
    code: 352,
    flag: getFlagIcon('lu'),
  },
  mo: {
    name: 'Macao SAR China',
    code: 853,
    flag: getFlagIcon('mo'),
  },
  mg: {
    name: 'Madagascar',
    code: 261,
    flag: getFlagIcon('mg'),
  },
  mw: {
    name: 'Malawi',
    code: 265,
    flag: getFlagIcon('mw'),
  },
  my: {
    name: 'Malaysia',
    code: 60,
    flag: getFlagIcon('my'),
  },
  mv: {
    name: 'Maldives',
    code: 960,
    flag: getFlagIcon('mv'),
  },
  ml: {
    name: 'Mali',
    code: 223,
    flag: getFlagIcon('ml'),
  },
  mt: {
    name: 'Malta',
    code: 356,
    flag: getFlagIcon('mt'),
  },
  mh: {
    name: 'Marshall Islands',
    code: 692,
    flag: getFlagIcon('mh'),
  },
  mq: {
    name: 'Martinique',
    code: 596,
    flag: getFlagIcon('mq'),
  },
  mr: {
    name: 'Mauritania',
    code: 222,
    flag: getFlagIcon('mr'),
  },
  mu: {
    name: 'Mauritius',
    code: 230,
    flag: getFlagIcon('mu'),
  },
  yt: {
    name: 'Mayotte',
    code: 262,
    flag: getFlagIcon('yt'),
  },
  mx: {
    name: 'Mexico',
    code: 52,
    flag: getFlagIcon('mx'),
  },
  fm: {
    name: 'Micronesia',
    code: 691,
    flag: getFlagIcon('fm'),
  },
  md: {
    name: 'Moldova',
    code: 373,
    flag: getFlagIcon('md'),
  },
  mc: {
    name: 'Monaco',
    code: 377,
    flag: getFlagIcon('mc'),
  },
  mn: {
    name: 'Mongolia',
    code: 976,
    flag: getFlagIcon('mn'),
  },
  me: {
    name: 'Montenegro',
    code: 382,
    flag: getFlagIcon('me'),
  },
  ma: {
    name: 'Morocco',
    code: 212,
    flag: getFlagIcon('ma'),
  },
  mz: {
    name: 'Mozambique',
    code: 258,
    flag: getFlagIcon('mz'),
  },
  mm: {
    name: 'Myanmar (Burma)',
    code: 95,
    flag: getFlagIcon('mm'),
  },
  na: {
    name: 'Namibia',
    code: 264,
    flag: getFlagIcon('na'),
  },
  nr: {
    name: 'Nauru',
    code: 674,
    flag: getFlagIcon('nr'),
  },
  np: {
    name: 'Nepal',
    code: 977,
    flag: getFlagIcon('np'),
  },
  nl: {
    name: 'Netherlands',
    code: 31,
    flag: getFlagIcon('nl'),
  },
  nc: {
    name: 'New Caledonia',
    code: 687,
    flag: getFlagIcon('nc'),
  },
  nz: {
    name: 'New Zealand',
    code: 64,
    flag: getFlagIcon('nz'),
  },
  ni: {
    name: 'Nicaragua',
    code: 505,
    flag: getFlagIcon('ni'),
  },
  ne: {
    name: 'Niger',
    code: 227,
    flag: getFlagIcon('ne'),
  },
  ng: {
    name: 'Nigeria',
    code: 234,
    flag: getFlagIcon('ng'),
  },
  nu: {
    name: 'Niue',
    code: 683,
    flag: getFlagIcon('nu'),
  },
  nf: {
    name: 'Norfolk Island',
    code: 672,
    flag: getFlagIcon('nf'),
  },
  kp: {
    name: 'North Korea',
    code: 850,
    flag: getFlagIcon('kp'),
  },
  mk: {
    name: 'North Macedonia',
    code: 389,
    flag: getFlagIcon('mk'),
  },
  no: {
    name: 'Norway',
    code: 47,
    flag: getFlagIcon('no'),
  },
  om: {
    name: 'Oman',
    code: 968,
    flag: getFlagIcon('om'),
  },
  pk: {
    name: 'Pakistan',
    code: 92,
    flag: getFlagIcon('pk'),
  },
  pw: {
    name: 'Palau',
    code: 680,
    flag: getFlagIcon('pw'),
  },
  ps: {
    name: 'Palestinian Territories',
    code: 970,
    flag: getFlagIcon('ps'),
  },
  pa: {
    name: 'Panama',
    code: 507,
    flag: getFlagIcon('pa'),
  },
  pg: {
    name: 'Papua New Guinea',
    code: 675,
    flag: getFlagIcon('pg'),
  },
  py: {
    name: 'Paraguay',
    code: 595,
    flag: getFlagIcon('py'),
  },
  pe: {
    name: 'Peru',
    code: 51,
    flag: getFlagIcon('pe'),
  },
  ph: {
    name: 'Philippines',
    code: 63,
    flag: getFlagIcon('ph'),
  },
  pl: {
    name: 'Poland',
    code: 48,
    flag: getFlagIcon('pl'),
  },
  pt: {
    name: 'Portugal',
    code: 351,
    flag: getFlagIcon('pt'),
  },
  qa: {
    name: 'Qatar',
    code: 974,
    flag: getFlagIcon('qa'),
  },
  ro: {
    name: 'Romania',
    code: 40,
    flag: getFlagIcon('ro'),
  },
  ru: {
    name: 'Russia',
    code: 7,
    flag: getFlagIcon('ru'),
  },
  rw: {
    name: 'Rwanda',
    code: 250,
    flag: getFlagIcon('rw'),
  },
  ws: {
    name: 'Samoa',
    code: 685,
    flag: getFlagIcon('ws'),
  },
  sm: {
    name: 'San Marino',
    code: 378,
    flag: getFlagIcon('sm'),
  },
  st: {
    name: 'São Tomé & Príncipe',
    code: 239,
    flag: getFlagIcon('st'),
  },
  sa: {
    name: 'Saudi Arabia',
    code: 966,
    flag: getFlagIcon('sa'),
  },
  sn: {
    name: 'Senegal',
    code: 221,
    flag: getFlagIcon('sn'),
  },
  rs: {
    name: 'Serbia',
    code: 381,
    flag: getFlagIcon('rs'),
  },
  sc: {
    name: 'Seychelles',
    code: 248,
    flag: getFlagIcon('sc'),
  },
  sl: {
    name: 'Sierra Leone',
    code: 232,
    flag: getFlagIcon('sl'),
  },
  sg: {
    name: 'Singapore',
    code: 65,
    flag: getFlagIcon('sg'),
  },
  sk: {
    name: 'Slovakia',
    code: 421,
    flag: getFlagIcon('sk'),
  },
  si: {
    name: 'Slovenia',
    code: 386,
    flag: getFlagIcon('si'),
  },
  sb: {
    name: 'Solomon Islands',
    code: 677,
    flag: getFlagIcon('sb'),
  },
  so: {
    name: 'Somalia',
    code: 252,
    flag: getFlagIcon('so'),
  },
  za: {
    name: 'South Africa',
    code: 27,
    flag: getFlagIcon('za'),
  },
  kr: {
    name: 'South Korea',
    code: 82,
    flag: getFlagIcon('kr'),
  },
  ss: {
    name: 'South Sudan',
    code: 211,
    flag: getFlagIcon('ss'),
  },
  es: {
    name: 'Spain',
    code: 34,
    flag: getFlagIcon('es'),
  },
  lk: {
    name: 'Sri Lanka',
    code: 94,
    flag: getFlagIcon('lk'),
  },
  sh: {
    name: 'St. Helena',
    code: 290,
    flag: getFlagIcon('sh'),
  },
  pm: {
    name: 'St. Pierre & Miquelon',
    code: 508,
    flag: getFlagIcon('pm'),
  },
  sd: {
    name: 'Sudan',
    code: 249,
    flag: getFlagIcon('sd'),
  },
  sr: {
    name: 'Suriname',
    code: 597,
    flag: getFlagIcon('sr'),
  },
  se: {
    name: 'Sweden',
    code: 46,
    flag: getFlagIcon('se'),
  },
  ch: {
    name: 'Switzerland',
    code: 41,
    flag: getFlagIcon('ch'),
  },
  sy: {
    name: 'Syria',
    code: 963,
    flag: getFlagIcon('sy'),
  },
  tw: {
    name: 'Taiwan',
    code: 886,
    flag: getFlagIcon('tw'),
  },
  tj: {
    name: 'Tajikistan',
    code: 992,
    flag: getFlagIcon('tj'),
  },
  tz: {
    name: 'Tanzania',
    code: 255,
    flag: getFlagIcon('tz'),
  },
  th: {
    name: 'Thailand',
    code: 66,
    flag: getFlagIcon('th'),
  },
  tl: {
    name: 'Timor-Leste',
    code: 670,
    flag: getFlagIcon('tl'),
  },
  tg: {
    name: 'Togo',
    code: 228,
    flag: getFlagIcon('tg'),
  },
  tk: {
    name: 'Tokelau',
    code: 690,
    flag: getFlagIcon('tk'),
  },
  to: {
    name: 'Tonga',
    code: 676,
    flag: getFlagIcon('to'),
  },
  tn: {
    name: 'Tunisia',
    code: 216,
    flag: getFlagIcon('tn'),
  },
  tr: {
    name: 'Turkey',
    code: 90,
    flag: getFlagIcon('tr'),
  },
  tm: {
    name: 'Turkmenistan',
    code: 993,
    flag: getFlagIcon('tm'),
  },
  tv: {
    name: 'Tuvalu',
    code: 688,
    flag: getFlagIcon('tv'),
  },
  ug: {
    name: 'Uganda',
    code: 256,
    flag: getFlagIcon('ug'),
  },
  ua: {
    name: 'Ukraine',
    code: 380,
    flag: getFlagIcon('ua'),
  },
  ae: {
    name: 'United Arab Emirates',
    code: 971,
    flag: getFlagIcon('ae'),
  },
  gb: {
    name: 'United Kingdom',
    code: 44,
    flag: getFlagIcon('gb'),
  },
  us: {
    name: 'United States',
    code: 1,
    flag: getFlagIcon('us'),
  },
  uy: {
    name: 'Uruguay',
    code: 598,
    flag: getFlagIcon('uy'),
  },
  uz: {
    name: 'Uzbekistan',
    code: 998,
    flag: getFlagIcon('uz'),
  },
  vu: {
    name: 'Vanuatu',
    code: 678,
    flag: getFlagIcon('vu'),
  },
  ve: {
    name: 'Venezuela',
    code: 58,
    flag: getFlagIcon('ve'),
  },
  vn: {
    name: 'Vietnam',
    code: 84,
    flag: getFlagIcon('vn'),
  },
  wf: {
    name: 'Wallis & Futuna',
    code: 681,
    flag: getFlagIcon('wf'),
  },
  ye: {
    name: 'Yemen',
    code: 967,
    flag: getFlagIcon('ye'),
  },
  zm: {
    name: 'Zambia',
    code: 260,
    flag: getFlagIcon('zm'),
  },
  zw: {
    name: 'Zimbabwe',
    code: 263,
    flag: getFlagIcon('zw'),
  },
};
